import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/modules/**/*.{js,ts,jsx,tsx,mdx}"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': {
          DEFAULT: 'var(--color-primary-500)',
          '50': 'var(--color-primary-50)',
          '100': 'var(--color-primary-100)',
          '200': 'var(--color-primary-200)',
          '300': 'var(--color-primary-300)',
          '400': 'var(--color-primary-400)',
          '500': 'var(--color-primary-500)',
          '600': 'var(--color-primary-600)',
          '700': 'var(--color-primary-700)',
          '800': 'var(--color-primary-800)',
          '900': 'var(--color-primary-900)',
        },
        'secondary': {
          DEFAULT: 'var(--color-secondary-500)',
          '50': 'var(--color-secondary-50)',
          '100': 'var(--color-secondary-100)',
          '200': 'var(--color-secondary-200)',
          '300': 'var(--color-secondary-300)',
          '400': 'var(--color-secondary-400)',
          '500': 'var(--color-secondary-500)',
          '600': 'var(--color-secondary-600)',
          '700': 'var(--color-secondary-700)',
          '800': 'var(--color-secondary-800)',
          '900': 'var(--color-secondary-900)',
        },
        'neutral': {
          DEFAULT: 'var(--color-neutral-500)',
          '50': 'var(--color-neutral-50)',
          '100': 'var(--color-neutral-100)',
          '200': 'var(--color-neutral-200)',
          '300': 'var(--color-neutral-300)',
          '400': 'var(--color-neutral-400)',
          '500': 'var(--color-neutral-500)',
          '600': 'var(--color-neutral-600)',
          '700': 'var(--color-neutral-700)',
          '800': 'var(--color-neutral-800)',
          '900': 'var(--color-neutral-900)',
          'white': 'var(--color-neutral-white)',
          'black': 'var(--color-neutral-black)',
        },
        'semantic': {
          'background-primary-default': 'var(--semantic-background-primary-default)',
          'background-primary-hover': 'var(--semantic-background-primary-hover)',
          'background-primary-pressed': 'var(--semantic-background-primary-pressed)',
          'background-primary-surface': 'var(--semantic-background-primary-surface)',
          'background-secondary-default': 'var(--semantic-background-secondary-default)',
          'background-secondary-hover': 'var(--semantic-background-secondary-hover)',
          'background-secondary-pressed': 'var(--semantic-background-secondary-pressed)',
          'background-secondary-surface': 'var(--semantic-background-secondary-surface)',
          'background-neutral-default': 'var(--semantic-background-neutral-default)',
          'background-neutral-hover': 'var(--semantic-background-neutral-hover)',
          'background-neutral-pressed': 'var(--semantic-background-neutral-pressed)',
          'background-neutral-surface': 'var(--semantic-background-neutral-surface)',
          'background-neutral-muted': 'var(--semantic-background-neutral-muted)',
          'background-disabled-default': 'var(--semantic-background-disabled-default)',
          'background-disabled-hover': 'var(--semantic-background-disabled-hover)',
          'background-disabled-pressed': 'var(--semantic-background-disabled-pressed)',
          'background-disabled-surface': 'var(--semantic-background-disabled-surface)',
          'background-success-default': 'var(--semantic-background-success-default)',
          'background-success-hover': 'var(--semantic-background-success-hover)',
          'background-success-pressed': 'var(--semantic-background-success-pressed)',
          'background-success-surface': 'var(--semantic-background-success-surface)',
          'background-warning-default': 'var(--semantic-background-warning-default)',
          'background-warning-hover': 'var(--semantic-background-warning-hover)',
          'background-warning-pressed': 'var(--semantic-background-warning-pressed)',
          'background-warning-surface': 'var(--semantic-background-warning-surface)',
          'background-error-default': 'var(--semantic-background-error-default)',
          'background-error-hover': 'var(--semantic-background-error-hover)',
          'background-error-pressed': 'var(--semantic-background-error-pressed)',
          'background-error-surface': 'var(--semantic-background-error-surface)',
          'background-info-default': 'var(--semantic-background-info-default)',
          'background-info-hover': 'var(--semantic-background-info-hover)',
          'background-info-pressed': 'var(--semantic-background-info-pressed)',
          'background-info-surface': 'var(--semantic-background-info-surface)',
          'text-primary-default': 'var(--semantic-text-primary-default)',
          'text-secondary-default': 'var(--semantic-text-secondary-default)',
          'text-neutral-primary': 'var(--semantic-text-neutral-primary)',
          'text-neutral-secondary': 'var(--semantic-text-neutral-secondary)',
          'text-neutral-brand': 'var(--semantic-text-neutral-brand)',
          'text-disabled-default': 'var(--semantic-text-disabled-default)',
          'text-disabled-secondary': 'var(--semantic-text-disabled-secondary)',
          'text-success-default': 'var(--semantic-text-success-default)',
          'text-warning-default': 'var(--semantic-text-warning-default)',
          'text-error-default': 'var(--semantic-text-error-default)',
          'text-info-default': 'var(--semantic-text-info-default)',
          'text-on-color': 'var(--semantic-text-on-color)',
          'text-on-light': 'var(--semantic-text-on-light)',
          'border-primary-default': 'var(--semantic-border-primary-default)',
          'border-secondary-default': 'var(--semantic-border-secondary-default)',
          'border-neutral-default': 'var(--semantic-border-neutral-default)',
          'border-neutral-subtle': 'var(--semantic-border-neutral-subtle)',
          'border-neutral-strong': 'var(--semantic-border-neutral-strong)',
          'border-disabled-default': 'var(--semantic-border-disabled-default)',
          'border-disabled-subtle': 'var(--semantic-border-disabled-subtle)',
          'border-disabled-strong': 'var(--semantic-border-disabled-strong)',
          'border-success-default': 'var(--semantic-border-success-default)',
          'border-warning-default': 'var(--semantic-border-warning-default)',
          'border-error-default': 'var(--semantic-border-error-default)',
          'border-info-default': 'var(--semantic-border-info-default)',
          'icon-primary-default': 'var(--semantic-icon-primary-default)',
          'icon-primary-light': 'var(--semantic-icon-primary-light)',
          'icon-primary-strong': 'var(--semantic-icon-primary-strong)',
          'icon-secondary-default': 'var(--semantic-icon-secondary-default)',
          'icon-secondary-light': 'var(--semantic-icon-secondary-light)',
          'icon-secondary-strong': 'var(--semantic-icon-secondary-strong)',
          'icon-neutral-primary': 'var(--semantic-icon-neutral-primary)',
          'icon-neutral-secondary': 'var(--semantic-icon-neutral-secondary)',
          'icon-neutral-light': 'var(--semantic-icon-neutral-light)',
          'icon-neutral-strong': 'var(--semantic-icon-neutral-strong)',
          'icon-disabled-default': 'var(--semantic-icon-disabled-default)',
          'icon-disabled-secondary': 'var(--semantic-icon-disabled-secondary)',
          'icon-disabled-light': 'var(--semantic-icon-disabled-light)',
          'icon-disabled-strong': 'var(--semantic-icon-disabled-strong)',
          'icon-success-default': 'var(--semantic-icon-success-default)',
          'icon-success-light': 'var(--semantic-icon-success-light)',
          'icon-success-strong': 'var(--semantic-icon-success-strong)',
          'icon-warning-default': 'var(--semantic-icon-warning-default)',
          'icon-warning-light': 'var(--semantic-icon-warning-light)',
          'icon-warning-strong': 'var(--semantic-icon-warning-strong)',
          'icon-error-default': 'var(--semantic-icon-error-default)',
          'icon-error-light': 'var(--semantic-icon-error-light)',
          'icon-error-strong': 'var(--semantic-icon-error-strong)',
          'icon-info-default': 'var(--semantic-icon-info-default)',
          'icon-info-light': 'var(--semantic-icon-info-light)',
          'icon-info-strong': 'var(--semantic-icon-info-strong)',
          'icon-on-color': 'var(--semantic-icon-on-color)',
          'icon-on-light': 'var(--semantic-icon-on-light)',
        },
      },
      spacing: {
        '0': 'var(--spacing-0)',
        '1': 'var(--spacing-1)',
        '2': 'var(--spacing-2)',
        '3': 'var(--spacing-3)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '8': 'var(--spacing-8)',
        '10': 'var(--spacing-10)',
        '12': 'var(--spacing-12)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      borderWidth: {
        '0': 'var(--border-width-0)',
        '1': 'var(--border-width-1)',
        '2': 'var(--border-width-2)',
        '4': 'var(--border-width-4)',
      },
      opacity: {
        '0': 'var(--opacity-0)',
        '25': 'var(--opacity-25)',
        '50': 'var(--opacity-50)',
        '75': 'var(--opacity-75)',
        '100': 'var(--opacity-100)',
      },
      boxShadow: {
        '0': 'var(--shadow-0)',
        '1': 'var(--shadow-1)',
        '2': 'var(--shadow-2)',
        '3': 'var(--shadow-3)',
        '4': 'var(--shadow-4)',
        '5': 'var(--shadow-5)',
      },
    }
  },
  plugins: [],
};
export default config;
